type TestType = {
  id: string;
  amount: number;
  status: "pending" | "processing" | "success" | "failed" | "completed";
  email: string;
  name: string;
  orderdate: string;
  paymethod: string;
  age: string;
  birthday: string;
  gender: string;
  address: string;
};

export const TestData: TestType[] = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "m@example.com",
    name: "Mark",
    orderdate: "2024-01-02",
    paymethod: "cash",
    age: "29",
    birthday: "1992-03-27",
    gender: "boy",
    address: "台北市信義區忠孝東路五段",
  },
  {
    id: "489e1d42",
    amount: 125,
    status: "processing",
    email: "example@gmail.com",
    name: "John",
    orderdate: "2024-01-03",
    paymethod: "credit card",
    age: "32",
    birthday: "1989-08-15",
    gender: "boy",
    address: "新北市板橋區中山路一段",
  },
  {
    id: "d294cf8e",
    amount: 75,
    status: "completed",
    email: "test@example.com",
    name: "Emily",
    orderdate: "2024-01-05",
    paymethod: "paypal",
    age: "27",
    birthday: "1994-05-10",
    gender: "girl",
    address: "台中市西屯區文心路一段",
  },
  {
    id: "e9b43c77",
    amount: 150,
    status: "pending",
    email: "info@example.com",
    name: "Sophia",
    orderdate: "2024-01-07",
    paymethod: "cash",
    age: "35",
    birthday: "1989-02-20",
    gender: "girl",
    address: "高雄市前鎮區中華五路",
  },
  {
    id: "17d6fbaf",
    amount: 200,
    status: "processing",
    email: "sales@example.com",
    name: "Michael",
    orderdate: "2024-01-10",
    paymethod: "credit card",
    age: "40",
    birthday: "1981-11-30",
    gender: "boy",
    address: "台南市安平區安北路",
  },
  {
    id: "bdac8b65",
    amount: 85,
    status: "pending",
    email: "support@example.com",
    name: "Emma",
    orderdate: "2024-01-12",
    paymethod: "cash",
    age: "25",
    birthday: "1996-09-18",
    gender: "girl",
    address: "基隆市中正區義一路",
  },
  {
    id: "90e32a57",
    amount: 120,
    status: "processing",
    email: "contact@example.com",
    name: "William",
    orderdate: "2024-01-15",
    paymethod: "credit card",
    age: "31",
    birthday: "1990-04-25",
    gender: "boy",
    address: "新竹市東區中華路二段",
  },
  {
    id: "6a3b7f4e",
    amount: 95,
    status: "completed",
    email: "service@example.com",
    name: "Olivia",
    orderdate: "2024-01-18",
    paymethod: "paypal",
    age: "28",
    birthday: "1993-12-07",
    gender: "girl",
    address: "苗栗縣苗栗市國華路",
  },
  {
    id: "f72b1e89",
    amount: 135,
    status: "pending",
    email: "info@example.com",
    name: "James",
    orderdate: "2024-01-20",
    paymethod: "cash",
    age: "33",
    birthday: "1988-07-12",
    gender: "boy",
    address: "彰化縣彰化市中山路",
  },
  {
    id: "c1f3e6a7",
    amount: 180,
    status: "processing",
    email: "sales@example.com",
    name: "Isabella",
    orderdate: "2024-01-25",
    paymethod: "credit card",
    age: "30",
    birthday: "1991-10-30",
    gender: "girl",
    address: "雲林縣斗六市雲林路",
  },
  {
    id: "4f63e2c1",
    amount: 110,
    status: "pending",
    email: "admin@example.com",
    name: "Ethan",
    orderdate: "2024-01-28",
    paymethod: "cash",
    age: "27",
    birthday: "1994-06-15",
    gender: "boy",
    address: "台南市中西區中山路",
  },
  {
    id: "8a96d5f2",
    amount: 95,
    status: "processing",
    email: "help@example.com",
    name: "Sophia",
    orderdate: "2024-02-03",
    paymethod: "credit card",
    age: "29",
    birthday: "1992-03-27",
    gender: "girl",
    address: "高雄市前鎮區瑞隆路",
  },
  {
    id: "b58a1c47",
    amount: 75,
    status: "completed",
    email: "contact@example.com",
    name: "Mia",
    orderdate: "2024-02-10",
    paymethod: "paypal",
    age: "26",
    birthday: "1995-01-22",
    gender: "girl",
    address: "屏東縣屏東市廣東路",
  },
  {
    id: "372e9b1f",
    amount: 120,
    status: "pending",
    email: "info@example.com",
    name: "Noah",
    orderdate: "2024-02-15",
    paymethod: "cash",
    age: "32",
    birthday: "1989-11-08",
    gender: "boy",
    address: "台東縣台東市中興路",
  },
  {
    id: "9d7f6e2b",
    amount: 150,
    status: "processing",
    email: "service@example.com",
    name: "Ava",
    orderdate: "2024-02-22",
    paymethod: "credit card",
    age: "34",
    birthday: "1987-04-30",
    gender: "girl",
    address: "宜蘭縣宜蘭市神農路",
  },
  {
    id: "3c8a1f6d",
    amount: 110,
    status: "completed",
    email: "info@example.com",
    name: "Ethan",
    orderdate: "2024-02-02",
    paymethod: "credit card",
    age: "27",
    birthday: "1994-06-15",
    gender: "boy",
    address: "台北市大安區信義路四段",
  },
  {
    id: "f9c7e2a4",
    amount: 95,
    status: "pending",
    email: "support@example.com",
    name: "Sophia",
    orderdate: "2024-02-05",
    paymethod: "paypal",
    age: "29",
    birthday: "1992-11-23",
    gender: "girl",
    address: "新北市板橋區民族路",
  },
  {
    id: "a2b3d7e1",
    amount: 120,
    status: "processing",
    email: "contact@example.com",
    name: "Mia",
    orderdate: "2024-02-10",
    paymethod: "cash",
    age: "32",
    birthday: "1989-03-28",
    gender: "girl",
    address: "桃園市桃園區中正路",
  },
];
